[project]
name = "daily-misc-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aisuite[all]>=0.1.7",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "yfinance>=0.2.51",
]
